version: 0.0
os: linux
files:
  - source: dist/
    destination: /var/www/html
permissions:
  - object: /var/www/html
    pattern: "**"
    mode: "0755"
    owner: root
    group: root
    type: 
      - files
      - directory
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
