# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- task: Cache@2
  inputs:
    key: 'package-lock.json'
    path: $(npm_config_cache)
  displayName: Cache NPM packages
- script: npm install --cache $(npm_config_cache)
  displayName: NPM Install Dependencies


- script: |
    npm run build
  displayName: 'npm build'
