version: 0.2

env:
  variables:
    ECR_REPO_NAME: samplevite

phases:
  pre_build:
    commands:
      - echo Loggin into the amazon docker...
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin

      - echo Logging in into ECR...
      - ECR_MAIN_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"
      - aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_MAIN_URI}

      - ECR_IMAGE_URI="891377277172.dkr.ecr.ap-southeast-2.amazonaws.com/samplevite:latest"
  build:
    commands:
      - docker build -t samplevite:latest .
      - docker tag samplevite:latest ${ECR_IMAGE_URI}
      - docker push ${ECR_IMAGE_URI}
  post_build:
    commands:
      - echo post build phase completed
