version: 0.2

# env:
#   variables:
#     DOCKERHUB_TOKEN:

phases:
  pre_build:
    commands:
      - echo Loggin into the amazon ECR...
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t samplevite:latest .
      - docker tag samplevite:latest ${DOCKERHUB_USER}/sampleviteproject:latest
      - docker push ${DOCKERHUB_USER}/sampleviteproject:latest
  post_build:
    commands:
      - echo post build phase completed
