version: 0.2

# env:
#   variables:
#     DOCKERHUB_USER: ajayakce

env:
  secrets-manager:
    DOCKERHUB_TOKEN: dockerhub:token
    DOCKERHUB_USER: dockerhub:user

phases:
  pre_build:
    commands:
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin
  build:
    commands:
      - docker build -t samplevite:latest .
  post_build:
    commands:
      - echo "we are in the post build phase"
      - docker tag samplevite:latest ${DOCKERHUB_USER}/samplevite:latest
      - docker push ${DOCKERHUB_USER}/samplevite:latest
