version: 0.2

env:
  variables:
    ECR_REPO_NAME: samplevite
    AWS_ACCOUNT_ID: "891377277172"

phases:
  pre_build:
    commands:
      - echo Loggin into the amazon docker...
      - echo ${DOCKERHUB_TOKEN} | docker login -u ${DOCKERHUB_USER} --password-stdin

      - echo Logging in into ECR...
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 891377277172.dkr.ecr.ap-southeast-2.amazonaws.com

      - ECR_IMAGE_URI="${ECR_MAIN_URI}/${ECR_REPO_NAME}:latest"
  build:
    commands:
      - docker build -t myecr .
      - docker tag myecr:latest 891377277172.dkr.ecr.ap-southeast-2.amazonaws.com/myecr:latest
      - docker push 891377277172.dkr.ecr.ap-southeast-2.amazonaws.com/myecr:latest
  post_build:
    commands:
      - echo post build phase completed
