version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - npm install
  pre_build:
    commands:
      - echo "we are in the pre build phase"
  build:
    commands:
      - npm run test --watchAll=false --browser=chrome
  post_build:
    commands:
      - echo "we are in the post build phase"
